import { query } from "@anthropic-ai/claude-agent-sdk";
import type { SDKMessage } from "@anthropic-ai/claude-agent-sdk";
import { readFileSync } from "fs";
import { join } from "path";
import { createSantaServer } from "./tools.ts";
import type { SolutionTask } from "./discovery.ts";
import type { SourceSolution } from "./source-reader.ts";

let langTxtCache: string | null = null;

async function fetchLangTxt(): Promise<string> {
  if (langTxtCache) return langTxtCache;

  const response = await fetch("https://eddmann.com/santa-lang/lang.txt");
  if (!response.ok) {
    throw new Error(`Failed to fetch lang.txt: ${response.status}`);
  }
  langTxtCache = await response.text();
  return langTxtCache;
}

function loadIdiomatic(): string {
  return readFileSync(
    join(import.meta.dirname, "..", "IDIOMATIC.md"),
    "utf-8"
  );
}

async function buildSystemPrompt(): Promise<string> {
  const langTxt = await fetchLangTxt();
  const idiomatic = loadIdiomatic();

  return `You are an expert santa-lang developer translating Advent of Code solutions into idiomatic santa-lang.

## Santa-Lang Language Specification

${langTxt}

## Idiomatic Santa-Lang Best Practices

${idiomatic}

## Instructions

You translate existing AoC solutions from other languages into idiomatic santa-lang. Follow these rules:

1. **Don't literally translate** — reimagine the solution using santa-lang's functional idioms
2. **Pipeline style** (\`|>\`) for data transformation chains
3. **Function composition** (\`>>\`) for parsing chains
4. **Underscore partial application** (\`_ + 1\`) for simple lambdas
5. **Pattern matching** for case analysis
6. **Lazy evaluation** with unbounded ranges for search problems
7. **fold** for stateful iteration instead of mutable state
8. **Sets** for uniqueness and membership tests

## Solution File Format

Every .santa file must have this structure:

\`\`\`santa
// Generated by santa-agent from <LANGUAGE> solution

input: read("aoc://YEAR/DAY")

// Parsing helpers using >> composition
let parse = lines >> map(ints)

part_one: {
  parse(input) |> ...
}

part_two: {
  parse(input) |> ...
}

// Example test with inline input from puzzle description
test: {
  input: "example input here"
  part_one: expected_answer
  part_two: expected_answer
}

// Real input test with submitted answers
test: {
  input: read("aoc://YEAR/DAY")
  part_one: real_answer
  part_two: real_answer
}
\`\`\`

Important notes:
- The FIRST line of every .santa file MUST be a comment: \`// Generated by santa-agent from <Language> solution\`
- Numeric answers are unquoted: \`part_one: 42\`
- String answers are quoted: \`part_one: "ABC"\`
- The \`input:\` line uses \`read("aoc://YEAR/DAY")\` where DAY is NOT zero-padded
- Example test inputs use actual newlines (multi-line strings), not \\n escape sequences
- Always include at least one example test from the puzzle description
- Always include the real input test with submitted answers at the bottom

## Workflow

1. Read the source solution to understand the algorithm
2. Write the .santa file using the Write tool
3. Run tests with the \`test\` tool
4. If tests fail, read the error, fix the solution, and re-test
5. Once tests pass, run \`verify\` to confirm answers match AoC
`;
}

function buildUserPrompt(
  task: SolutionTask,
  source: SourceSolution,
  puzzleProse: string,
  submittedAnswers: { partOne: string | null; partTwo: string | null }
): string {
  return `Create a santa-lang solution for **${task.year} Day ${task.day}**.

The first line of the file MUST be: \`// Generated by santa-agent from ${source.language} solution\`

## Target File
Write to: \`${task.targetPath}\`

## Source Solution (${source.language})

\`\`\`${source.language.toLowerCase()}
${source.code}
\`\`\`

## Puzzle Description

${puzzleProse}

## Expected Answers

- Part One: ${submittedAnswers.partOne || "unknown"}
- Part Two: ${submittedAnswers.partTwo || "unknown"}

## Real Input Test Block

Use these in the final test block:
\`\`\`
test: {
  input: read("aoc://${task.year}/${task.day}")
  ${submittedAnswers.partOne ? `part_one: ${isNumeric(submittedAnswers.partOne) ? submittedAnswers.partOne : `"${submittedAnswers.partOne}"`}` : ""}
  ${submittedAnswers.partTwo ? `part_two: ${isNumeric(submittedAnswers.partTwo) ? submittedAnswers.partTwo : `"${submittedAnswers.partTwo}"`}` : ""}
}
\`\`\`

## Example Tests

Extract example test cases from BOTH:
1. **The puzzle description** — look for example inputs and their expected outputs
2. **The source code and test files above** — look for inline test data, assertions, doctests, or hardcoded example inputs with expected results

Create example test blocks using these. If the input is very short (single-line), you may have multiple small test blocks.

## Steps

1. Write the solution to \`${task.targetPath}\`
2. Run \`test\` to verify
3. Fix any failures and re-test
4. Once passing, run \`verify\` with year=${task.year} day=${task.day}
`;
}

function isNumeric(s: string): boolean {
  return /^-?\d+$/.test(s);
}

export interface AgentEvent {
  type: "text" | "tool_call" | "tool_result" | "result" | "error";
  content: string;
  cost?: number;
  duration?: number;
}

export async function* runAgent(
  task: SolutionTask,
  source: SourceSolution,
  puzzleProse: string,
  submittedAnswers: { partOne: string | null; partTwo: string | null },
): AsyncGenerator<AgentEvent> {
  const systemPrompt = await buildSystemPrompt();
  const userPrompt = buildUserPrompt(task, source, puzzleProse, submittedAnswers);
  const aocToken = process.env.AOC_SESSION;
  const santaServer = createSantaServer(aocToken);

  try {
    for await (const message of query({
      prompt: userPrompt,
      options: {
        mcpServers: { santa: santaServer },
        tools: [
          "Read",
          "Edit",
          "Write",
          "Glob",
          "Grep",
          "mcp__santa__test",
          "mcp__santa__verify",
        ],
        allowedTools: [
          "Read",
          "Edit",
          "Write",
          "Glob",
          "Grep",
          "mcp__santa__test",
          "mcp__santa__verify",
        ],
        systemPrompt,
        maxTurns: 100,
        model: "opus",
        effort: "max",
      },
    })) {
      const msg = message as SDKMessage;

      if (msg.type === "assistant" && msg.message?.content) {
        for (const block of msg.message.content) {
          if ("text" in block && block.text) {
            yield { type: "text", content: block.text };
          } else if ("name" in block) {
            yield {
              type: "tool_call",
              content: `${block.name}(${JSON.stringify(block.input || {}).slice(0, 100)})`,
            };
          }
        }
      } else if (msg.type === "result") {
        const resultMsg = msg as any;
        yield {
          type: "result",
          content: resultMsg.subtype === "success" ? "completed" : "failed",
          cost: resultMsg.total_cost_usd,
          duration: resultMsg.duration_ms,
        };
      }
    }
  } catch (error: any) {
    yield { type: "error", content: error.message || String(error) };
  }
}
